### ISSUE TITLE
Inlets in Karst network simulation

### ISSUE THREAD

**Issue by jChappuis** [randlab/pyKasso#2]
Adding a long list of inlets sometimes gives the following error.
      2 for i in range(1):
      3     model_parameters['sks']['seed'] = i
----> 4     app.model.generate(model_parameters=model_parameters)

File z:\\projects\\2024_Hoelloch\\pyKasso-master\\pykasso\\model\\sks.py:101, in SKS.generate(self, model_parameters, export_settings)
     98 self._initialize()
    100 ### Build the geological model
--> 101 self._build()
    103 ### Compute the karst network
    104 self._compute()

File z:\\projects\\2024_Hoelloch\\pyKasso-master\\pykasso\\model\\sks.py:252, in SKS._build(self)
    250 self._build_geological_features()  # Construct the geological features
    251 self._build_domain()               # Construct the domain
--> 252 self._build_point_features()       # Construct the points features
    253 self._build_conceptual_model()     # Construct the conceptual model
    254 self._construct_fmm_variables()    # Construct fmm features

File z:\\projects\\2024_Hoelloch\\pyKasso-master\\pykasso\\model\\sks.py:470, in SKS._build_point_features(self)
    465 self._points = {
    466     'outlets': {},
    467     'inlets': {},
    468 }
    469 self._build_model_outlets()
--> 470 self._build_model_inlets()
    471 # del self._points
    472 return None

File z:\\projects\\2024_Hoelloch\\pyKasso-master\\pykasso\\model\\wrappers.py:135, in _parameters_validation.<locals>..<locals>._wrapper(*args, **kwargs)
    133 msg = \"'{}' parameters have been validated.\".format(feature)
    134 logger.info(msg)
--> 135 result = function(*args, **kwargs)
    136 return model

File z:\\projects\\2024_Hoelloch\\pyKasso-master\\pykasso\\model\\wrappers.py:153, in _memoize.<locals>..<locals>._wrapper(*args, **kwargs)
    150 memoization = model.project._memoization
    151 if model.model_parameters[feature] is not memoization['settings'][feature]:
    152     # print('is not') # TODO
--> 153     result = function(*args, **kwargs)
    154     memoization['settings'][feature] = model.model_parameters[feature]
    155     memoization['model'][feature] = getattr(model, feature)

File z:\\projects\\2024_Hoelloch\\pyKasso-master\\pykasso\\model\\wrappers.py:182, in _logging.<locals>..<locals>._wrapper(*args, **kwargs)
    180     msg = \"Critical error during '{}'\".format(function._name_)
    181     logger.critical(msg)
--> 182     raise err
    183 else:
    184     logger.debug(\"'{}' went well\".format(function._name_))

File z:\\projects\\2024_Hoelloch\\pyKasso-master\\pykasso\\model\\wrappers.py:178, in _logging.<locals>..<locals>._wrapper(*args, **kwargs)
    176     logger = logging.getLogger(\".\")
    177 try:
--> 178     result = function(*args, **kwargs)
    179 except Exception as err:
    180     msg = \"Critical error during '{}'\".format(function._name_)

File z:\\projects\\2024_Hoelloch\\pyKasso-master\\pykasso\\model\\sks.py:496, in SKS._build_model_inlets(self)
    492 \"\"\"
    493 Build the inlets.
    494 \"\"\"
    495 self._set_rng('inlets')
--> 496 self.inlets = self._construct_feature_points('inlets')
    497 if self.model_parameters['inlets']['shuffle']:
    498     pts = self.inlets.sample(frac=1, random_state=self.rng['sks'])

File z:\\projects\\2024_Hoelloch\\pyKasso-master\\pykasso\\model\\sks.py:536, in SKS._construct_feature_points(self, kind)
    534 if len(point) == 2:
    535     if self._is_point_valid(point):
--> 536         point = self._2D_to_3D_point(kind, point)
    537         validated_points.append(point)
    538     else:

File z:\\projects\\2024_Hoelloch\\pyKasso-master\\pykasso\\model\\sks.py:677, in SKS._2D_to_3D_point(self, kind, point)
    674 valid_cells = self._points[kind]['valid_cells']
    675 column_valid_cells = valid_cells[(valid_cells['i'] == i)
    676                                  & (valid_cells['j'] == j)]
--> 677 i_, j_, k_ = self.rng[kind].choice(column_valid_cells)
    678 z = (self.grid.zmin + (k_ + self.rng[kind].random()) * self.grid.dz)
    679 x, y = point

File numpy\\\\random\\\\_generator.pyx:866, in numpy.random._generator.Generator.choice()

ValueError: a cannot be empty unless no samples are taken"
}

**Comment by fmiville** [comment]
Hi, thank you for your message.
Can you provide the configuration dictionary or .yaml configuration file you're using?
Best regards,

**Comment by jChappuis** [comment]
Hello,
Here's my complete project [https://drive.switch.ch/index.php/s/ICbjGfwQ8Q5ohyU](url)
You should be able to test it.
Best regards.

**Comment by fmiville** [comment]
Thank you for your anwser,
I've understood that the point generator was inspecting the wrong variable when transforming a 2D point into a 3D point.
I've commit a fix, please download the last version of pyKasso. Your project should return now a valid message error.
One of your point is probably invalid because it does not match with your current inlet subdomain configuration.
Please tell me if you require any further information.
Best,
